<?php include $phireHeader; ?>
    <h1 class="entities-header"><?=$title; ?></h1>
<?php if (count($types) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'entity-types', 'add')): ?>
        <nav><a href="<?=$phireUri . '/entities/types/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/modules'; ?>">Back</a></nav>
    </nav>
<?php if ($acl->isAllowed($user->role, 'entity-types', 'remove')): ?>
    <form id="entity-types-form" action="<?=$phireUri . '/entities/types/remove'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/entities/types?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/entities/types?sort=name';?>">Name</a></th>
                <th><a href="<?=$phireUri . '/entities/types?sort=order';?>">Order</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'entity-types', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'entity-types', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_entity_types" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($types as $type): ?>
            <tr>
                <td><?=$type->id; ?></td>
                <td><?=$type->name; ?></td>
                <td><?=$type->order; ?></td>
                <td><?php if (($acl->isAllowed($user->role, 'entity-types', 'edit') && ($acl->isAllowed($user->role, 'entity-type-' . $type->id, 'edit')))): ?><a class="edit-link" href="<?=$phireUri . '/entities/types/edit/' . $type->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if (($acl->isAllowed($user->role, 'entity-types', 'remove') && ($acl->isAllowed($user->role, 'entity-type-' . $type->id, 'remove')))): ?><input type="checkbox" name="rm_entity_types[]" id="rm_entity_types<?=$i++; ?>" value="<?=$type->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'entity-types', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'entity-types', 'add')): ?>
        <nav><a href="<?=$phireUri . '/entities/types/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/modules'; ?>">Back</a></nav>
    </nav>
    <p>There are currently no entity types.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
